version: '3'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
        - MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: on-failure
    expose:
      - "3306"

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mariadb
    expose:
      - "9000"
    restart: unless-stopped

networks:
  inception:

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/repinat/data/html'
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/repinat/data/mariadb'
